### ISSUE TITLE
Dedent (#d) did not show error, when going out of level 0 

### ISSUE THREAD

**Issue by glennDittmann** [platformer/typst-algorithms#5]
Hey first of all cool package !

I was accidentally having one `#d` to much on my last line, which just kept the specific part of the pseudo code from rendering, but did not show any error message; so it was a bit tricky to find.

Would be cool if there could be some indication / error, when one accidentally dedents out of scope.

Minimal Example:
```
#algo(
  title: "Fib",
  parameters: ("n",)
)[
  if $n < 0$:#i\        // use #i to indent the following lines
    return null#d\      // use #d to to dedent the following lines
  if $n = 0$ or $n = 1$: #i  
    return $n$ #d #d
  new line \  # <- only gets rendered, when removing the second dedent in the line above
  return #smallcaps("Fib")$(n-1) +$ #smallcaps("Fib")$(n-2)$
]
```

**Comment by platformer** [comment]
The library should report the message `assertion failed: algo: dedented too much` if you have an excess dedent. I tried the following code (basically just removed your comment), and the error is thrown as expected:

```typst
#algo(
  title: "Fib",
  parameters: ("n",)
)[
  if $n < 0$:#i\        // use #i to indent the following lines
    return null#d\      // use #d to to dedent the following lines
  if $n = 0$ or $n = 1$: #i  
    return $n$ #d #d
  new line \
  return #smallcaps("Fib")$(n-1) +$ #smallcaps("Fib")$(n-2)$
]
```

Can you confirm if this is the case for you as well? I'd also like to know if you're using the web app or the latest version of the Typst CLI.

**Comment by glennDittmann** [comment]
Yes, when I run `typst compile` on this snippet I also get this error.

But not in the webapp.. So must be a specific behavior related to that environment.

**Comment by platformer** [comment]
After some messing around, I managed to coax the web app into displaying the expected error message using exactly the same code as above. But it seems very temperamental.

Given that the CLI behaves as expected, I'm inclined to call this an issue with the web app. A similar problem for a different library has been previously discovered as well: https://github.com/typst/typst/issues/1802. As such, I'll close this issue for now.

**Comment by glennDittmann** [comment]
Great thanks !
