### ISSUE TITLE
`code` only recognizes `raw` text that is in a `sequence`

### ISSUE THREAD

**Issue by emilyyyylime** [platformer/typst-algorithms#7]
This works:
````
code[
```
code here
```
]
````
But these examples don't:
````
code[```
code here
```]
````
````
code(body: raw(...))
````

Passing a raw block directly rather then a `sequence` containing it should be supported

**Comment by platformer** [comment]
Thanks for reporting this! Fixed by 5e17cf3d75abb359d35c180b08be151a6389be64
